package com.piano.view;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.piano.MusicaMDI;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *Pagina principal donde abarcara el sistema
 * @author Smit BZ :D
 */
public class index extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(index.class.getName());

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
        notaMusica();
        setIconImage(new ImageIcon(getClass().getResource("/img/icon.png")).getImage()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoModos = new javax.swing.ButtonGroup();
        modoTema = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        nota1 = new javax.swing.JButton();
        nota2 = new javax.swing.JButton();
        nota3 = new javax.swing.JButton();
        nota4 = new javax.swing.JButton();
        nota5 = new javax.swing.JButton();
        nota6 = new javax.swing.JButton();
        nota7 = new javax.swing.JButton();
        nota8 = new javax.swing.JButton();
        nota9 = new javax.swing.JButton();
        nota10 = new javax.swing.JButton();
        nota11 = new javax.swing.JButton();
        nota12 = new javax.swing.JButton();
        nota13 = new javax.swing.JButton();
        nota14 = new javax.swing.JButton();
        nota15 = new javax.swing.JButton();
        nota16 = new javax.swing.JButton();
        nota17 = new javax.swing.JButton();
        nota18 = new javax.swing.JButton();
        nota19 = new javax.swing.JButton();
        nota20 = new javax.swing.JButton();
        nota21 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        tecla = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        temaClaro = new javax.swing.JCheckBoxMenuItem();
        temaOscuro = new javax.swing.JCheckBoxMenuItem();
        guia = new javax.swing.JCheckBoxMenuItem();
        modos = new javax.swing.JMenu();
        menu1 = new javax.swing.JRadioButtonMenuItem();
        menu2 = new javax.swing.JRadioButtonMenuItem();
        menu3 = new javax.swing.JRadioButtonMenuItem();
        menu4 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Melion");

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("do");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 246, 55, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("re");
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 246, 55, 30));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("mi");
        jLayeredPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 246, 55, 30));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("fa");
        jLayeredPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 246, 55, 30));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("sol");
        jLayeredPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 246, 55, 30));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("la");
        jLayeredPane1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 246, 55, 30));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("si");
        jLayeredPane1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 246, 55, 30));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("do");
        jLayeredPane1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 246, 55, 30));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("re");
        jLayeredPane1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 246, 55, 30));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("mi");
        jLayeredPane1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 246, 55, 30));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("fa");
        jLayeredPane1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 246, 55, 30));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("sol");
        jLayeredPane1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 246, 55, 30));

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("la");
        jLayeredPane1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 246, 55, 30));

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("si");
        jLayeredPane1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 246, 55, 30));

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("do");
        jLayeredPane1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 246, 55, 30));

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("re");
        jLayeredPane1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 246, 55, 30));

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("mi");
        jLayeredPane1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 246, 55, 30));

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("fa");
        jLayeredPane1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(935, 246, 55, 30));

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("sol");
        jLayeredPane1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 246, 55, 30));

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("la");
        jLayeredPane1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1045, 246, 55, 30));

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("si");
        jLayeredPane1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 246, 55, 30));

        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("re#");
        jLayeredPane1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 155, 40, 35));

        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("do#");
        jLayeredPane1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 155, 40, 35));

        jLabel24.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("fa#");
        jLayeredPane1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 155, 40, 35));

        jLabel25.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("sol#");
        jLayeredPane1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 155, 40, 35));

        jLabel26.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("la#");
        jLayeredPane1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 155, 40, 35));

        jLabel27.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("re#");
        jLayeredPane1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 155, 40, 35));

        jLabel28.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("do#");
        jLayeredPane1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 155, 40, 35));

        jLabel29.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("fa#");
        jLayeredPane1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 155, 40, 35));

        jLabel30.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("sol#");
        jLayeredPane1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 155, 40, 35));

        jLabel31.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("la#");
        jLayeredPane1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 155, 40, 35));

        jLabel33.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("sol#");
        jLayeredPane1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1025, 155, 40, 35));

        jLabel34.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("la#");
        jLayeredPane1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 155, 40, 35));

        jLabel32.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("fa#");
        jLayeredPane1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 155, 40, 35));

        jLabel35.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("re#");
        jLayeredPane1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 155, 40, 35));

        jLabel36.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("do#");
        jLayeredPane1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 155, 40, 35));

        btn1.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 0, 40, 210));

        btn2.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 40, 210));

        btn3.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 40, 210));

        btn4.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 0, 40, 210));

        btn5.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 40, 210));

        btn6.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 40, 210));

        btn7.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 0, 40, 210));

        btn8.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 0, 40, 210));

        btn9.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 40, 210));

        btn10.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 0, 40, 210));

        btn11.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 0, 40, 210));

        btn12.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 40, 210));

        btn13.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(btn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 40, 210));

        btn14.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(btn14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1025, 0, 40, 210));

        btn15.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(btn15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, 40, 210));
        jLayeredPane1.add(nota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 55, 315));
        jLayeredPane1.add(nota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 0, 55, 315));
        jLayeredPane1.add(nota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 55, 315));
        jLayeredPane1.add(nota4, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 0, 55, 315));
        jLayeredPane1.add(nota5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 55, 315));
        jLayeredPane1.add(nota6, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 0, 55, 315));
        jLayeredPane1.add(nota7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 55, 315));
        jLayeredPane1.add(nota8, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 0, 55, 315));
        jLayeredPane1.add(nota9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 55, 315));
        jLayeredPane1.add(nota10, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 0, 55, 315));
        jLayeredPane1.add(nota11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 55, 315));
        jLayeredPane1.add(nota12, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 0, 55, 315));
        jLayeredPane1.add(nota13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 55, 315));
        jLayeredPane1.add(nota14, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 0, 55, 315));
        jLayeredPane1.add(nota15, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 55, 315));
        jLayeredPane1.add(nota16, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 0, 55, 315));
        jLayeredPane1.add(nota17, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 55, 315));
        jLayeredPane1.add(nota18, new org.netbeans.lib.awtextra.AbsoluteConstraints(935, 0, 55, 315));
        jLayeredPane1.add(nota19, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 55, 315));
        jLayeredPane1.add(nota20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1045, 0, 55, 315));
        jLayeredPane1.add(nota21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 55, 315));

        tecla.setText("Opciones");
        tecla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaActionPerformed(evt);
            }
        });

        jMenu3.setText("Tema");

        modoTema.add(temaClaro);
        temaClaro.setSelected(true);
        temaClaro.setText("Claro");
        temaClaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temaClaroActionPerformed(evt);
            }
        });
        jMenu3.add(temaClaro);

        modoTema.add(temaOscuro);
        temaOscuro.setText("Oscuro");
        temaOscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temaOscuroActionPerformed(evt);
            }
        });
        jMenu3.add(temaOscuro);

        tecla.add(jMenu3);

        guia.setSelected(true);
        guia.setText("Mostrar Guia");
        guia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiaActionPerformed(evt);
            }
        });
        tecla.add(guia);

        modos.setText("Modo");

        grupoModos.add(menu1);
        menu1.setSelected(true);
        menu1.setText("Clasico");
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });
        modos.add(menu1);

        grupoModos.add(menu2);
        menu2.setText("Eléctrico");
        menu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu2ActionPerformed(evt);
            }
        });
        modos.add(menu2);

        grupoModos.add(menu3);
        menu3.setText("Sintetizador");
        menu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu3ActionPerformed(evt);
            }
        });
        modos.add(menu3);

        grupoModos.add(menu4);
        menu4.setText("Organo");
        menu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu4ActionPerformed(evt);
            }
        });
        modos.add(menu4);

        tecla.add(modos);

        jMenuBar1.add(tecla);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void guiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiaActionPerformed
        if(guia.isSelected() == true){
            mostrarGuia();
        }else{
            ocultarGuia();
        }
        
    }//GEN-LAST:event_guiaActionPerformed

    private void teclaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaActionPerformed

    }//GEN-LAST:event_teclaActionPerformed

    private void menu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu2ActionPerformed
        MusicaMDI.cambiarInstrumento(4);
    }//GEN-LAST:event_menu2ActionPerformed

    private void menu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu3ActionPerformed
        MusicaMDI.cambiarInstrumento(80);
    }//GEN-LAST:event_menu3ActionPerformed

    private void menu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu4ActionPerformed
        MusicaMDI.cambiarInstrumento(16);
    }//GEN-LAST:event_menu4ActionPerformed

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
         MusicaMDI.cambiarInstrumento(0);
    }//GEN-LAST:event_menu1ActionPerformed

    private void temaClaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaClaroActionPerformed
        TemaClaro();
    }//GEN-LAST:event_temaClaroActionPerformed

    private void temaOscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaOscuroActionPerformed
        TemaOscuro();
    }//GEN-LAST:event_temaOscuroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            FlatMacLightLaf.setup();
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new index().setVisible(true));
    }
    
    private void TemaOscuro() {
        try {
                UIManager.setLookAndFeel(new FlatMacDarkLaf());
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
    }

    private void TemaClaro() {
        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
    }
    
    public void ocultarGuia(){
        jLabel1.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        jLabel2.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jLabel22.setVisible(false);
        jLabel23.setVisible(false);
        jLabel24.setVisible(false);
        jLabel25.setVisible(false);
        jLabel26.setVisible(false);
        jLabel27.setVisible(false);
        jLabel28.setVisible(false);
        jLabel29.setVisible(false);
        jLabel3.setVisible(false);
        jLabel30.setVisible(false);
        jLabel31.setVisible(false);
        jLabel32.setVisible(false);
        jLabel33.setVisible(false);
        jLabel34.setVisible(false);
        jLabel35.setVisible(false);
        jLabel36.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
    }
    
    public void mostrarGuia(){
        jLabel1.setVisible(true);
        jLabel10.setVisible(true);
        jLabel11.setVisible(true);
        jLabel12.setVisible(true);
        jLabel13.setVisible(true);
        jLabel14.setVisible(true);
        jLabel15.setVisible(true);
        jLabel16.setVisible(true);
        jLabel17.setVisible(true);
        jLabel18.setVisible(true);
        jLabel19.setVisible(true);
        jLabel2.setVisible(true);
        jLabel20.setVisible(true);
        jLabel21.setVisible(true);
        jLabel22.setVisible(true);
        jLabel23.setVisible(true);
        jLabel24.setVisible(true);
        jLabel25.setVisible(true);
        jLabel26.setVisible(true);
        jLabel27.setVisible(true);
        jLabel28.setVisible(true);
        jLabel29.setVisible(true);
        jLabel3.setVisible(true);
        jLabel30.setVisible(true);
        jLabel31.setVisible(true);
        jLabel32.setVisible(true);
        jLabel33.setVisible(true);
        jLabel34.setVisible(true);
        jLabel35.setVisible(true);
        jLabel36.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabel8.setVisible(true);
        jLabel9.setVisible(true);
    }
    
    private void asignarNota(JButton boton, int nota){
        boton.addActionListener(e -> MusicaMDI.sonidoEfecto(nota));
    }
    
    private void notaMusica(){
        asignarNota(btn1, 49);
        asignarNota(btn2, 51);
        asignarNota(btn3, 54);
        asignarNota(btn4, 56);
        asignarNota(btn5, 58);
        asignarNota(btn6, 61);
        asignarNota(btn7, 63);
        asignarNota(btn8, 66);
        asignarNota(btn9, 68);
        asignarNota(btn10, 70);
        asignarNota(btn11, 73);
        asignarNota(btn12, 75);
        asignarNota(btn13, 78);
        asignarNota(btn14, 80);
        asignarNota(btn15, 82);
        
        asignarNota(nota1, 48);
        asignarNota(nota2, 50);
        asignarNota(nota3, 52);
        asignarNota(nota4, 53);
        asignarNota(nota5, 55);
        asignarNota(nota6, 57);
        asignarNota(nota7, 59);
        asignarNota(nota8, 60);
        asignarNota(nota9, 62);
        asignarNota(nota10, 64);
        asignarNota(nota11, 65);
        asignarNota(nota12, 67);
        asignarNota(nota13, 69);
        asignarNota(nota14, 71);
        asignarNota(nota15, 72);
        asignarNota(nota16, 74);
        asignarNota(nota17, 76);
        asignarNota(nota18, 77);
        asignarNota(nota19, 79);
        asignarNota(nota20, 81);
        asignarNota(nota21, 83);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.ButtonGroup grupoModos;
    private javax.swing.JCheckBoxMenuItem guia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem menu1;
    private javax.swing.JRadioButtonMenuItem menu2;
    private javax.swing.JRadioButtonMenuItem menu3;
    private javax.swing.JRadioButtonMenuItem menu4;
    private javax.swing.ButtonGroup modoTema;
    private javax.swing.JMenu modos;
    private javax.swing.JButton nota1;
    private javax.swing.JButton nota10;
    private javax.swing.JButton nota11;
    private javax.swing.JButton nota12;
    private javax.swing.JButton nota13;
    private javax.swing.JButton nota14;
    private javax.swing.JButton nota15;
    private javax.swing.JButton nota16;
    private javax.swing.JButton nota17;
    private javax.swing.JButton nota18;
    private javax.swing.JButton nota19;
    private javax.swing.JButton nota2;
    private javax.swing.JButton nota20;
    private javax.swing.JButton nota21;
    private javax.swing.JButton nota3;
    private javax.swing.JButton nota4;
    private javax.swing.JButton nota5;
    private javax.swing.JButton nota6;
    private javax.swing.JButton nota7;
    private javax.swing.JButton nota8;
    private javax.swing.JButton nota9;
    private javax.swing.JMenu tecla;
    private javax.swing.JCheckBoxMenuItem temaClaro;
    private javax.swing.JCheckBoxMenuItem temaOscuro;
    // End of variables declaration//GEN-END:variables
}
